# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiFran' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weibo
  pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
  pod "Alamofire"
  pod "SDWebImage"
end
